# Practical 1

In [ ]:
dict = {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}

In [1]:
def list_of_dict(heights):
    keys=heights.keys()
    values = zip(*[heights[k] for k in keys]) 
    result = [dict(zip(keys,v )) for v in values]
    return result

heights = {'Boys':[72,68,70,69,74], 'Girls':[63,65,69,62,61]}
print("\n ORIGINAL DICTIONARY OF LISTS ::" , heights)
print("\n NOW LIST OF DICTIONARIES :: \n",list_of_dict(heights))



 ORIGINAL DICTIONARY OF LISTS :: {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}

 NOW LIST OF DICTIONARIES :: 
 [{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {'Boys': 74, 'Girls': 61}]


# Prcatical 2

In [2]:
import numpy as np

In [3]:
#part a
arr = np.random.randint(1,50,(4,6))
arr

array([[43, 31, 14, 22, 10, 44],
       [22,  3, 46, 30, 23, 48],
       [30, 42,  1, 28, 39, 19],
       [20, 31, 42, 11, 37,  9]])

In [4]:
#along the second axis
#Mean
print('Mean of the array: ',arr.mean(axis=1))
#standard deviation
print('Standard Deviation of the array: ',arr.std(axis=1))
#variance
print('Variance of the array: ',arr.var(axis=1))

Mean of the array:  [27.33333333 28.66666667 26.5        25.        ]
Standard Deviation of the array:  [13.18669363 15.33695609 13.64734406 12.5565388 ]
Variance of the array:  [173.88888889 235.22222222 186.25       157.66666667]


In [5]:
#part b
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
arr1 = np.array(B)
arr1

array([56, 48, 22, 41, 78, 91, 24, 46,  8, 33])

In [6]:
arr1.sort()
arr1

array([ 8, 22, 24, 33, 41, 46, 48, 56, 78, 91])

In [7]:
#part c
m = int(input('Enter the number of rows(m): '))
n = int(input('Enter the number of columns(n): '))
arr2 = np.random.randint(1,100,(m,n))
print(arr2)
print('Shape: ',arr2.shape)
# print('Type: ',arr2.type)
print('Data Type: ',arr2.dtype)
arr2 = arr2.reshape(n,m)
print('After reshaping: \n',arr2)
print('New Shape: ',arr2.shape)

Enter the number of rows(m): 2
Enter the number of columns(n): 3
[[58 24 62]
 [69  5 63]]
Shape:  (2, 3)
Data Type:  int32
After reshaping: 
 [[58 24]
 [62 69]
 [ 5 63]]
New Shape:  (3, 2)
