# Practical 1

In [1]:
dict = {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}

# Prcatical 2

In [4]:
import numpy as np

In [3]:
#part a
arr = np.random.randint(1,50,(4,6))
arr

array([[16, 36, 40, 10, 44, 23],
       [13, 47, 30, 40, 29, 35],
       [14, 33, 49, 17, 36, 29],
       [28, 46, 22, 46,  3, 24]])

In [6]:
#along the second axis
#Mean
print('Mean of the array: ',arr.mean(axis=1))
#standard deviation
print('Standard Deviation of the array: ',arr.std(axis=1))
#variance
print('Variance of the array: ',arr.var(axis=1))

Mean of the array:  [28.16666667 32.33333333 29.66666667 28.16666667]
Standard Deviation of the array:  [12.62823116 10.57775444 11.77096239 14.85952743]
Variance of the array:  [159.47222222 111.88888889 138.55555556 220.80555556]


In [8]:
#part b
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
arr1 = np.array(B)
arr1

array([56, 48, 22, 41, 78, 91, 24, 46,  8, 33])

In [11]:
arr1.sort()
arr1

array([ 8, 22, 24, 33, 41, 46, 48, 56, 78, 91])

In [11]:
#part c
m = int(input('Enter the number of rows(m): '))
n = int(input('Enter the number of columns(n): '))
arr2 = np.random.randint(1,100,(m,n))
print(arr2)
print('Shape: ',arr2.shape)
# print('Type: ',arr2.type)
print('Data Type: ',arr2.dtype)
arr2 = arr2.reshape(n,m)
print('After reshaping: \n',arr2)
print('New Shape: ',arr2.shape)

Enter the number of rows(m): 3
Enter the number of columns(n): 4
[[34 52 44  4]
 [12 89 31 84]
 [ 4 73 56 22]]
Shape:  (3, 4)
Data Type:  int32
After reshaping: 
 [[34 52 44]
 [ 4 12 89]
 [31 84  4]
 [73 56 22]]
New Shape:  (4, 3)
